/**
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 * Output:
 * e
 * Explanation:
 * 'e' is the letter that was added.
*/

// Wrong Solution
// If input as s = "a", t = "aa", expected output is 'a', but this method will return null
// the tricky part is condition to judge when same char but different digits.
public class Solution {
    public char findTheDifference(String s, String t) {
        char[] a = s.toCharArray();
        char[] b = t.toCharArray();

        char result = '\0';
        
        for(int i = 0; i < b.length; i++) {
            char x = b[i];
            boolean notExist = true;
            int j;
            for(j = 0; j < a.length; j++) {
                char y = a[j];
                // This condition cause the error, only consideration on x and y are different
                // chars, but even if x, y are same char, because of different digits issue,
                // the additional char will also happen.
                if(x == y) {
                    notExist = false;
                    break;
                }
            }
            
            if(notExist) {
                result = b[i];
            } 
        }
        
        return result;
    }
}

// Solution 1: 这种解法比较直接，建立以个map对应字符串s，key为字符，value就是该字符出现的次数。首先遍历字符串s，
// 来建立这个map，然后再遍历字符串t。对t中出现的每个字符，都从map中减一，当最后剩下一个value值为1时，则说明该
// 字符就是多出的字符
// Refer to 
// https://my.oschina.net/styshoo/blog/752872
public class Solution {
    public char findTheDifference(String s, String t) {
        char result = '\0';
        
        Map<Character, Integer> map = new HashMap<Character, Integer>();
        char[] a = s.toCharArray();
        char[] b = t.toCharArray();
        
        for(int i = 0; i < b.length; i++) {
            if(!map.containsKey(b[i])) {
                map.put(b[i], 1);
            } else {
                map.put(b[i], map.get(b[i]) + 1);
            }
        }
        
        for(int j = 0; j < a.length; j++) {
            if(map.containsKey(a[j]) && map.get(a[j]) > 0) {
                map.put(a[j], map.get(a[j]) - 1);
            }
        }
        
        for(Character c : map.keySet()) {
            if(map.get(c) == 1) {
                result = c;
            }
        } 
        
        return result;
    }
}

